const readline = require("readline");
const { iCloudDriveDirectory } = require("./config");
const { spawn } = require("child_process");
const recursiveList = require("./util/recursiveList");

// The purpose of this module is to keep iCloud Drive in sync
// and it achieves this by running `brctl monitor` to detect blog
// folders with changes and then it recursively lists their contents
// in order to force iCloud to sync the contents of the folder. It seems
// like using ls as opposed to readdir actually forces iCloud drive to
// push the names of new files and folders to the local system.

// If eventually we run into scaling issues with chokidar we could potentially
// use the information generated by this module to trigger syncs...
module.exports = () => {
  function startMonitor() {
    const monitorProcess = spawn("brctl", [
      "monitor",
      "-i",
      iCloudDriveDirectory,
    ]);

    const rl = readline.createInterface({
      input: monitorProcess.stdout,
      crlfDelay: Infinity,
    });

    rl.on("line", (line) => {
      const match = line.match(/blog_[a-fA-F0-9]+/);
      if (match) {
        const blogId = match[0];
        console.log("Recursively listing contents of:", blogId);
        recursiveList(`${iCloudDriveDirectory}/${blogId}`, 0).catch((error) => {
          console.error(
            `Failed to recursively list contents of ${blogId}:`,
            error
          );
        });
      }
    });

    monitorProcess.stderr.on("data", (data) => {
      console.error(`stderr: ${data}`);
    });

    monitorProcess.on("close", (code) => {
      rl.close();
      console.warn(
        `brctl monitor exited with code ${code}, restarting in 1s...`
      );
      setTimeout(startMonitor, 1000);
    });
  }

  startMonitor();
};
